[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Project to develop a Streamlit app to host some DP-100 questions"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.3",
    "streamlit>=1.44.1",
]
